# Generated by Django 4.0.3 on 2023-12-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_criminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('searching', 'Searching'), ('found', 'Found')], default='searching', max_length=20)),
            ],
        ),
    ]
