# Generated by Django 4.0.3 on 2023-12-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_missingperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='missing_persons/'),
        ),
    ]
