# Generated by Django 4.0.3 on 2023-12-05 23:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_missingperson_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='missing_persons/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('searching', 'Searching'), ('found', 'Found')], default='reported', max_length=20),
        ),
    ]
